// This is a placeholder for AWS Amplify configuration
// In a real application, this would be generated by the Amplify CLI
const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "YOUR_IDENTITY_POOL_ID",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "YOUR_USER_POOL_ID",
  "aws_user_pools_web_client_id": "YOUR_USER_POOL_WEB_CLIENT_ID",
  "oauth": {},
  "aws_appsync_graphqlEndpoint": "YOUR_APPSYNC_ENDPOINT",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_cloud_logic_custom": [
    {
      "name": "api",
      "endpoint": "YOUR_API_GATEWAY_ENDPOINT",
      "region": "us-east-1"
    }
  ]
};

export default awsmobile;